# Generated by Django 4.0.4 on 2022-05-22 04:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('street_address', models.CharField(max_length=100)),
                ('additional_information', models.TextField(blank=True, max_length=1000)),
                ('center_of_population', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_preferred', models.BooleanField(default=False)),
                ('card_number', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', 'CVV should be valid: 0325')])),
                ('expiration_date', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^(0[1-9]|1[0-2])\\/([0-9]{2})$', 'Expiration date should be valid: 01/91')])),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='PayPalAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'PayPal Account',
                'verbose_name_plural': 'PayPal Accounts',
            },
        ),
        migrations.CreateModel(
            name='AccountPersonalData',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personal_data', serialize=False, to='domain.paypalaccount')),
                ('full_name', models.CharField(blank=True, max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('date_of_birth', models.DateField(blank=True)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('avatar', models.ImageField(blank=True, upload_to='accounts/icons')),
                ('password', models.CharField(max_length=48, validators=[django.core.validators.MinLengthValidator(8)])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'verbose_name': 'Account Personal Data',
                'verbose_name_plural': 'Accounts Personal Data',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('finished_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('auto_payment', 'Auto_Payment'), ('payment', 'Payment'), ('refund', 'Refund'), ('transfer', 'Transfer')], max_length=50)),
                ('payment_method', models.CharField(choices=[('paypal_balance', 'PayPal_Balance'), ('payment', 'Payment'), ('card', 'Card'), ('rewards', 'Rewards')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_from', to='domain.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_to', to='domain.card')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_account', to='domain.paypalaccount'),
        ),
        migrations.AddField(
            model_name='card',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_address', to='domain.billingaddress'),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='account_personal_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address_account', to='domain.accountpersonaldata'),
        ),
    ]
